name: resoterre
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  # Dev tools and testing
  - pip >=25.2
  # - bump-my-version >=1.2.3  # temporarily disabled due to incompatibility with click>=8.3
  - click >=8.3.0
  - coverage >=7.5.0
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.18.2
  - numpy >=1.26.4
  - numpydoc >=1.9.0
  - pre-commit >=3.5.0
  - pytest >=8.3.2
  - pytest-cov >=5.0.0
  - pyyaml >=6.0.1
  - ruff >=0.12.0
  - tox >=4.30.3
  - types-click >=7.1.0
  - xarray >=2024.6.0
  - vulture >=2.14
  - watchdog >=4.0.0
  - pytorch >=2.7.1
  - ruff >=0.13.3
  - scikit-learn >=1.6.1
  - ipykernel >=6.28.0
  - types-PyYAML >=6.0.12
  - dacite >=1.8.1
