# snakemake -s rdps_to_hrdps_on_disk.smk --config config_yaml=rdps_to_hrdps_on_disk.yaml -j1 --directory=/path/to/workflow/outputs

path_workflow: /path/to/workflow/outputs
path_logs: /path/to/logs
path_ml_data: &path_ml_data /path/to/ml_data
path_figures: /path/to/figures

# Dataset specifications
dataset:
  type: RDPSToHRDPS
  integrity_rdps_directory: /path/to/rdps_integrity_check
  integrity_hrdps_directory: /path/to/hrdps_integrity_check
  rdps_hrdps_intersection_lz4_path: /path/to/rdps_hrdps_intersection.lz4
  path_ml_data: *path_ml_data
  path_grids: /path/to/grids
  grid_input_for_ml: 8km_north_america_ml
  grid_output_for_ml: 2km_north_america_ml
  start_datetime: "2017-05-22 00:00:00"
  end_datetime: "2024-05-30 18:00:00"
  rdps_variables:
    - TT_model_levels
    - PR
    - HU850
    - GZ500
    - PC
  hrdps_variables:
    - HRDPS_P_TT_10000
    - HRDPS_P_PR_SFC
  save_batch_size: 16
  only_from_ml_data: true
  dataset_manager: RDPSToHRDPS

path_hrdps_regrid: /path/to/hrdps_regrid
path_rdps_regrid: /path/to/rdps_regrid
path_hrdps_mask: /path/to/hrdps_mask
path_hrdps_mf: /path/to/hrdps_mf
path_hrdps_sftlf: /path/to/hrdps_sftlf
temporal_window: None
save_batch_size: 16
rdps_window_size: None
overlap_factor: None  # preferably a divisor of rdps_window_size
hrdps_required_unmasked_fraction: None
normalize: True
train_fraction: 0.8
validation_fraction: 0.1
test_fraction: 0.1
random_seed: 0
# anomaly_variables:
# variables_with_temporal_context:
skip_load: False
# plot_transform_keys: 
# plot_transform_counts: 
# plot_transform_max_png_files: 0
# max_save_count: int = 10000  # ToDo: this belongs to the data generation, not the dataset

hrdps_extent_coordinates:
  lat_min: 0.0
  lat_max: 0.0
  lon_min: 0.0
  lon_max: 0.0
hrdps_shape:
  lat_size: 0
  lon_size: 0
rdps_extent_coordinates:
  lat_min: 0.0
  lat_max: 0.0
  lon_min: 0.0
  lon_max: 0.0
rdps_shape:
  lat_size: 0
  lon_size: 0

framework: pytorch
framework_version: '2.9.0+cu130'
